### ISSUE TITLE
gh-pages require PATH other than local

### ISSUE THREAD

**Issue by will-s-205** [Clare-Boniface/monkey-tinder#2]
It seem like local setup have no issues with finding path to CSS and JS file. However, it is not accepted by gh-pages which is causing the app to break web layout during the deploy phase.
![2023-08-16_14-14-45](https://github.com/Clare-Boniface/monkey-tinder/assets/97144951/ecf41b34-bad5-4299-a237-962b839adce0)

**Comment by Clare-Boniface** [comment]
Thankyou Will. Really appreciate your support with this. I’ve merged and closed the PR.
